# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DirectionPointTool
                                 A QGIS plugin
 Adds in point features by dragging in a direction/bearing
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-22
        copyright            : (C) 2026 by LC Ecological Services
        email                : David@deltavgeo.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DirectionPointTool class from file DirectionPointTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .direction_point_tool import DirectionPointTool
    return DirectionPointTool(iface)
